version: "3.7"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:

  lavalink:
    <<: *restart_policy
    image: ghcr.io/freyacodes/lavalink:latest
    container_name: lavalink
    environment:
        - _JAVA_OPTIONS=-Xmx6G
        - SERVER_PORT=2333
        - LAVALINK_SERVER_PASSWORD=youshallnotpass
    networks:
        - lavalink
    expose:
        - 2333
    ports:
        - 2333:2333


  mr-robot:
    <<: *restart_policy
    image: ghcr.io/mr-robot-discord-bot/mr-robot:latest
    container_name: mr-robot
    tty: true
    environment:
      - BOT_TOKEN=YOUR BOT TOKEN
      - ON_JOIN_WEBHOOK=WEBHOOK_URL
      - AI_API_KEY=GEMNI AI API KEY
      - GIT_TOKEN=GIT_API_TOKEN
      - GIT_DB_REPO=OWNER/REPO
      - NSFW_API=NSFW API
    networks:
        - lavalink
    depends_on:
        - lavalink


networks:
    lavalink:
        name: lavalink
