name: Build and push Docker image to GHCR

on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/mr-robot-discord-bot/mr-robot:latest
          cache-to: type=inline
          tags: |
            ghcr.io/knownblackhat/mr-robot:latest
            ghcr.io/knownblackhat/mr-robot:${{ github.sha }}
